name: appetizer
description: An application for digitalzing IIT Roorkee Mess

version: 2.0.3+17

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  firebase_analytics: ^10.0.3
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.3
  firebase_remote_config: ^3.0.3
  flare_flutter: ^3.0.2
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.0.5
  flutter_svg: ^1.0.3
  flutter_swiper: ^1.1.6
  fluttertoast: ^8.0.8
  get: ^4.3.8
  get_it: ^7.2.0
  http: ^0.13.3
  intl: ^0.17.0
  path_provider: ^2.0.3
  pedantic: ^1.11.0
  provider: ^6.0.0
  qr_flutter: ^4.0.0
  sembast: ^3.1.0+2
  sentry_flutter: ^6.0.0
  shared_preferences: ^2.0.7
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.10
  share_plus: ^6.2.0
  package_info_plus: ^3.0.1
  connectivity_plus: ^3.0.2
  connectivity_for_web: ^0.4.0+1
  flutter_inappwebview: ^5.4.3+7
  flutter_screenutil: ^5.5.3+2
  lottie: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/icons/logo_rounded.png"
  image_path_ios: "assets/icons/logo_squared.png"
  android: true
  ios: true

flutter_native_splash:
  background_image: "assets/images/splash_bg.png"
  image: "assets/icons/splash_icon.png"
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
          style: italic

    - family: Lobster_Two
      fonts:
        - asset: assets/fonts/Lobster_Two/LobsterTwo-Regular.ttf
        - asset: assets/fonts/Lobster_Two/LobsterTwo-Italic.ttf
        - asset: assets/fonts/Lobster_Two/LobsterTwo-Bold.ttf
        - asset: assets/fonts/Lobster_Two/LobsterTwo-BoldItalic.ttf
          weight: 700
