name: Remove Old Artifacts

on: [push, pull_request]

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove Old Artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: "1 week"
          skip-recent: 7
